#!/usr/bin/env python3
"""Embed built web assets into PROGMEM arrays for the firmware."""
from __future__ import annotations

import argparse
import mimetypes
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_DIST = ROOT / 'webui' / 'dist'
DEFAULT_OUTPUT = ROOT / 'src' / 'web_assets_generated.cpp'

CONTENT_TYPES = {
    '.html': 'text/html; charset=utf-8',
    '.htm': 'text/html; charset=utf-8',
    '.css': 'text/css; charset=utf-8',
    '.js': 'application/javascript',
}

mimetypes.add_type('application/javascript', '.js')


def guess_content_type(path: pathlib.Path) -> str:
    return CONTENT_TYPES.get(path.suffix.lower(), mimetypes.guess_type(path.name)[0] or 'application/octet-stream')


def slugify(name: str) -> str:
    return ''.join(ch if ch.isalnum() else '_' for ch in name)


def emit_byte_array(name: str, data: bytes) -> str:
    if not data:
        return f'static const uint8_t {name}[] PROGMEM = {{}};\n'
    lines = []
    for idx in range(0, len(data), 16):
        chunk = ', '.join(f'0x{byte:02x}' for byte in data[idx : idx + 16])
        lines.append(f'  {chunk}')
    body = ',\n'.join(lines)
    return f'static const uint8_t {name}[] PROGMEM = {{\n{body}\n}};\n'


def generate(dist: pathlib.Path, output: pathlib.Path) -> None:
    if not dist.exists():
        raise SystemExit(f"Dist folder '{dist}' does not exist. Run 'npm run build' inside webui first.")

    files = sorted([path for path in dist.rglob('*') if path.is_file()])
    if not files:
        raise SystemExit(f"No files found under '{dist}'.")

    output.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append('// Auto-generated by tools/embed_web_assets.py. Do not edit manually.')
    lines.append('#include <pgmspace.h>')
    lines.append('#include "web_assets.h"\n')

    table_entries: list[str] = []
    for path in files:
        rel = path.relative_to(dist)
        web_path = '/' + '/'.join(rel.parts)
        identifier = slugify(web_path.strip('/')) or 'root'
        array_name = f'WEB_ASSET_{identifier}'
        data = path.read_bytes()
        lines.append(emit_byte_array(array_name, data))
        content_type = guess_content_type(path)
        table_entries.append(f'{{"{web_path}", "{content_type}", {array_name}, sizeof({array_name})}}')

    lines.append('const EmbeddedAsset EMBEDDED_ASSETS[] = {')
    for idx, entry in enumerate(table_entries):
        suffix = ',' if idx + 1 < len(table_entries) else ''
        lines.append(f'  {entry}{suffix}')
    lines.append('};\n')
    lines.append('const size_t EMBEDDED_ASSET_COUNT = sizeof(EMBEDDED_ASSETS) / sizeof(EMBEDDED_ASSETS[0]);\n')

    output.write_text('\n'.join(lines), encoding='utf-8')


def main() -> int:
    parser = argparse.ArgumentParser(description='Embed built web assets into PROGMEM arrays.')
    parser.add_argument('--dist', type=pathlib.Path, default=DEFAULT_DIST)
    parser.add_argument('--output', type=pathlib.Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    generate(args.dist, args.output)
    return 0


if __name__ == '__main__':
    sys.exit(main())
